server:
  port: 8080
# URL Rating-service
ratingServiceFindByIdHotel: http://localhost:8082/rating/getRatingByIdHotel/
# Eureka - True because it will be registered in eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotel/**
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/rating/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**