# Fetching config from server at : http://localhost:8083
spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://localhost:8083
  config:
    import: optional:configserver:http://localhost:8083
