server:
  port: 8083 
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: part5-Eureka
          uri: https://github.com/MoniFrias/Microservices-SpringBoot.git
          search-paths: config-data
